//
// myblas_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_MYBLAS_ISPC_H
#define ISPC_MYBLAS_ISPC_H

#include <stdint.h>

#ifdef __cplusplus
namespace ispc {
#endif // __cplusplus


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
    extern void dotprod_ispc(float *a, float *b, int32_t n, float *sum);
    extern void matT_vec_ispc(const float alpha, float *A, float *x, float *y, const int64_t n, const int64_t m);
    extern void mat_vec_ispc(float alpha, float *A, float *x, float *y, const int64_t n, const int64_t m, float *Ax);
#ifdef __cplusplus
}
#endif // __cplusplus

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // ISPC_MYBLAS_ISPC_H
