//
// myblas_ispc.h
// (Header automatically generated by the ispc compiler.)
// DO NOT EDIT THIS FILE.
//

#ifndef ISPC_MYBLAS_ISPC_H
#define ISPC_MYBLAS_ISPC_H

#include <stdint.h>

#ifdef __cplusplus
namespace ispc {
#endif // __cplusplus


///////////////////////////////////////////////////////////////////////////
// Functions exported from ispc code
///////////////////////////////////////////////////////////////////////////
#ifdef __cplusplus
extern "C" {
#endif // __cplusplus
    extern void backsubst_L_ispc(double *L, double *b, double *x, int64_t n, int64_t k);
    extern void backsubst_Lt_ispc(double *L, double *b, double *x, int64_t n, int64_t k);
    extern void cholsolve_L_ispc(double *A, double *b, double *x, int64_t n, int64_t k, double *tmp);
    extern double dotprod_ispc(double *a, double *b, int32_t n);
    extern double dotprod_ispc(double *a, double *b, int64_t astart, int64_t bstart, int32_t n);
    extern void matT_vec_ispc(const double alpha, double *A, double *x, double *y, const int64_t n, const int64_t m);
    extern void mat_vec_ispc(double alpha, double *A, double *x, double *y, const int64_t n, const int64_t m, double *Ax);
#ifdef __cplusplus
}
#endif // __cplusplus

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // ISPC_MYBLAS_ISPC_H
